---
title: "project pt 1"
author: "andrew.estes"
date: "9/8/2021"
output: word_document
---


# Ames Housing
### Correlation between several variables OR 
### Heat map of houses by different variables (pool, price, etc)

## Abstract
We want to see if there is a grouping/clustering houses based off factors such as pools, porches, and prices. 
We are searching for geographic patterns.


\newpage
## Introduction
We are utilizing the Ames, Iowa house dataset curated by Dean DeCock of Truman State University. This dataset describes the sale of individual residential property in Ames, Iowa from 2006 to 2010. The dataset contains 2930 observations and 80 variables involved in assessing home values. We are analyzing the correlation between several variables to see what is the most influential category when it comes to assessing home value. Furthermore, we are creating cool maps that may show a pattern of houses with pools or price of houses.
This could be useful knowledge for a realtor or pool installer/cleaner. If there are certain patterns that show themselves after the analysis of data, it would be wise for a business person to focus their attentions on the pattern. 

\newpage
## Methods
The data was provided by Dean DeCock of Truman State University. It is already fairly clean although there are some missing data points within each variable. We will utilize the programming language R to do the analysis and R Markdown to transform it into a readable output. 

\newpage
## Results
Here are our results

\newpage
## Further Discussion
Based off the results, this is what we think

\newpage
## References
```{r}
#install.packages("AmesHousing")
library(AmesHousing)      
AmesData<-make_ames( )
```

\newpage
## Appendix
For excess graphs and stuff